#version: '3.8'
#
#services:
#  postgres-db:
#    image: postgres:15
#    container_name: postgres-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 862004
#      POSTGRES_DB: mydb
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  springboot-app:
#    build: .
#    container_name: springboot-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/mydb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 862004
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#    depends_on:
#      - springboot-app
#
#volumes:
#  postgres_data:
